### ISSUE TITLE
Error when accessing website

### ISSUE THREAD

**Issue by frahz** [Richel7/WeatherApp#1]
I follow the [website](https://weather-app-richel7.vercel.app/) link, once I enter a city and try to search nothing happens.
Your `config.js` is not getting sourced/ or isn't available. So Weather API won't respond (I think).

Look into this https://vercel.com/docs/concepts/projects/environment-variables

Error:
![image](https://user-images.githubusercontent.com/57733316/232913432-e41e5c0e-8bcf-41eb-9032-3862ae52d034.png)

**Comment by Richel7** [comment]
Fixed.
